ARCH="aarch64"
CPU_FLAG="--cpu=armv8-a"
ABI="arm64-v8a"
ADDI_CFLAGS="-DANDROID"
ADDI_LDFLAGS=""
COMPILED_VERSION="21"
TOOLCHAIN_PLATFORM="aarch64-linux-android-4.9"
BIN_PREFIX="aarch64-linux-android-"
